import { createClient } from "@supabase/supabase-js";

export type SiteSettings = Record<string, string>;

export const siteSettingDefaults: SiteSettings = {
  announcement_visible: "true",
  announcement_fr: "Boutique en ligne · Retrait à Nice",
  announcement_en: "Online shop · Pickup in Nice",

  brand_name: "ICHIGO ICHIE",
  brand_subtitle_fr: "Maison de matcha · Nice",
  brand_subtitle_en: "Japanese matcha house · Nice",
  brand_logo_url: "/brand-mark.svg",

  nav_menu_fr: "La carte",
  nav_menu_en: "Menu",
  nav_shop_fr: "Boutique",
  nav_shop_en: "Shop",
  nav_house_fr: "La maison",
  nav_house_en: "Our house",
  nav_cart_fr: "Panier",
  nav_cart_en: "Cart",
  nav_contact_fr: "Contact",
  nav_contact_en: "Contact",

  home_hero_visible: "true",
  home_eyebrow_fr: "Un moment. Une tasse. Des souvenirs.",
  home_eyebrow_en: "One moment. One cup. Memories.",
  home_title_fr: "Le matcha japonais,\ndans sa forme la plus douce.",
  home_title_en: "Japanese matcha,\nin its gentlest form.",
  home_intro_fr: "Une maison japonaise à Nice dédiée au matcha, aux boissons fraîches et aux douceurs japonaises.",
  home_intro_en: "A Japanese matcha house in Nice dedicated to matcha, fresh drinks and Japanese treats.",
  home_primary_cta_fr: "Voir la carte",
  home_primary_cta_en: "View the menu",
  home_secondary_cta_fr: "Découvrir la boutique",
  home_secondary_cta_en: "Discover the shop",
  home_hero_image_url: "/products/matcha-coconut-cloud.webp",
  home_hero_note1_fr: "Nice",
  home_hero_note1_en: "Nice",
  home_hero_note2_fr: "",
  home_hero_note2_en: "",

  home_featured_visible: "true",
  featured_eyebrow_fr: "ICHIGO ICHIE",
  featured_eyebrow_en: "ICHIGO ICHIE",
  featured_title_fr: "Nos incontournables",
  featured_title_en: "Our favourites",

  home_story_visible: "true",
  story_eyebrow_fr: "一期一会",
  story_eyebrow_en: "一期一会",
  story_title_fr: "Chaque rencontre est unique.",
  story_title_en: "Every encounter is unique.",
  story_text_fr: "Ichigo Ichie invite à vivre chaque moment comme s’il ne devait jamais se reproduire. À Nice, nous partageons cette philosophie autour du matcha, d’un geste simple et d’une tasse préparée avec soin.",
  story_text_en: "Ichigo Ichie invites you to experience each moment as if it could never happen again. In Nice, we share this philosophy through matcha, simple gestures and carefully prepared cups.",
  story_link_fr: "Voir la carte →",
  story_link_en: "View the menu →",
  story_card_label: "ICHIGO ICHIE",
  story_card_title_fr: "Maison de matcha\nà Nice",
  story_card_title_en: "Matcha house\nin Nice",
  story_image_url: "",
  story_address_label_fr: "Adresse",
  story_address_label_en: "Address",
  story_hours_label_fr: "Horaires",
  story_hours_label_en: "Opening hours",
  story_phone_label_fr: "Téléphone",
  story_phone_label_en: "Phone",
  story_maps_cta_fr: "Itinéraire",
  story_maps_cta_en: "Directions",
  story_instagram_cta_fr: "Instagram",
  story_instagram_cta_en: "Instagram",
  store_address: "14 rue Centrale · Vieux Nice",
  store_maps_url: "",

  menu_eyebrow_fr: "ICHIGO ICHIE",
  menu_eyebrow_en: "ICHIGO ICHIE",
  menu_title_fr: "La carte",
  menu_title_en: "Menu",
  menu_intro_fr: "Boissons et desserts à découvrir directement dans notre maison du Vieux Nice.",
  menu_intro_en: "Drinks and desserts to discover in our Vieux Nice matcha house.",
  menu_info_note_fr: "La carte est présentée à titre informatif. Les boissons et desserts ne sont pas commandables en ligne.",
  menu_info_note_en: "The menu is for information only. Drinks and desserts are not available for online ordering.",
  menu_all_fr: "Tout",
  menu_all_en: "All",
  menu_empty_fr: "Aucun article dans cette catégorie.",
  menu_empty_en: "No items in this category.",

  shop_eyebrow_fr: "ICHIGO ICHIE",
  shop_eyebrow_en: "ICHIGO ICHIE",
  shop_title_fr: "La boutique",
  shop_title_en: "Shop",
  shop_intro_fr: "Matcha japonais et accessoires sélectionnés pour votre rituel quotidien.",
  shop_intro_en: "Japanese matcha and accessories selected for your daily ritual.",
  shop_all_fr: "Tout",
  shop_all_en: "All",
  shop_empty_fr: "Aucun produit dans cette catégorie.",
  shop_empty_en: "No products in this category.",

  catalog_sort_label_fr: "Trier par",
  catalog_sort_label_en: "Sort by",
  catalog_sort_recommended_fr: "Ordre recommandé",
  catalog_sort_recommended_en: "Recommended",
  catalog_sort_price_asc_fr: "Prix : croissant",
  catalog_sort_price_asc_en: "Price: low to high",
  catalog_sort_price_desc_fr: "Prix : décroissant",
  catalog_sort_price_desc_en: "Price: high to low",
  catalog_sort_name_asc_fr: "Nom : A → Z",
  catalog_sort_name_asc_en: "Name: A → Z",
  catalog_sort_name_desc_fr: "Nom : Z → A",
  catalog_sort_name_desc_en: "Name: Z → A",

  mobile_menu_label_fr: "Carte",
  mobile_menu_label_en: "Menu",
  mobile_house_label_fr: "Maison",
  mobile_house_label_en: "About",


  contact_visible: "true",
  contact_eyebrow_fr: "ICHIGO ICHIE",
  contact_eyebrow_en: "ICHIGO ICHIE",
  contact_title_fr: "Une question ? Écrivez-nous.",
  contact_title_en: "A question? Write to us.",
  contact_intro_fr: "Pour une question sur la boutique, nos produits ou votre commande, envoyez-nous un message.",
  contact_intro_en: "For a question about the shop, our products or your order, send us a message.",
  contact_reply_note_fr: "Nous répondons généralement sous 24 à 48 h ouvrées.",
  contact_reply_note_en: "We usually reply within 1–2 business days.",
  contact_first_name_label_fr: "Prénom",
  contact_first_name_label_en: "First name",
  contact_last_name_label_fr: "Nom",
  contact_last_name_label_en: "Last name",
  contact_email_label_fr: "E-mail",
  contact_email_label_en: "Email",
  contact_phone_label_fr: "Téléphone",
  contact_phone_label_en: "Phone",
  contact_message_label_fr: "Message",
  contact_message_label_en: "Message",
  contact_submit_fr: "Envoyer le message",
  contact_submit_en: "Send message",
  contact_sending_fr: "Envoi…",
  contact_sending_en: "Sending…",
  contact_success_fr: "Merci. Votre message a bien été envoyé.",
  contact_success_en: "Thank you. Your message has been sent.",
  contact_error_fr: "L’envoi a échoué. Réessayez dans un instant.",
  contact_error_en: "The message could not be sent. Please try again shortly.",
  contact_required_note_fr: "* Champs obligatoires",
  contact_required_note_en: "* Required fields",
  contact_privacy_fr: "Vos informations sont utilisées uniquement pour répondre à votre demande.",
  contact_privacy_en: "Your information is used only to respond to your request.",
  contact_first_name_required: "true",
  contact_last_name_required: "false",
  contact_email_required: "true",
  contact_phone_required: "false",
  contact_message_required: "true",

  cart_eyebrow_fr: "ICHIGO ICHIE",
  cart_eyebrow_en: "ICHIGO ICHIE",
  cart_title_fr: "Votre panier",
  cart_title_en: "Your cart",
  cart_empty_title_fr: "Votre panier est vide",
  cart_empty_title_en: "Your cart is empty",
  cart_empty_text_fr: "Ajoutez un matcha, un accessoire ou un coffret depuis la Boutique.",
  cart_empty_text_en: "Add matcha, accessories or a gift set from the Shop.",

  checkout_eyebrow_fr: "ICHIGO ICHIE",
  checkout_eyebrow_en: "ICHIGO ICHIE",
  checkout_title_fr: "Finaliser la commande",
  checkout_title_en: "Complete order",
  checkout_intro_fr: "Livraison en France métropolitaine ou retrait gratuit à Nice.",
  checkout_intro_en: "Delivery in metropolitan France or free pickup in Nice.",

  footer_brand: "ICHIGO ICHIE",
  footer_show_logo: "true",
  footer_tagline_fr: "Un moment. Une tasse. Des souvenirs.",
  footer_tagline_en: "One moment. One cup. Memories.",
  footer_open_prefix_fr: "Ouvert",
  footer_open_prefix_en: "Open",
  footer_copyright_name: "Ichigo Ichie",
  footer_nav_title_fr: "Explorer",
  footer_nav_title_en: "Explore",
  footer_visit_title_fr: "Nous rendre visite",
  footer_visit_title_en: "Visit us",
  footer_follow_title_fr: "Suivre",
  footer_follow_title_en: "Follow",
  footer_legal_title_fr: "Informations",
  footer_legal_title_en: "Information",
  footer_maps_label_fr: "Google Maps",
  footer_maps_label_en: "Google Maps",
  footer_location_fr: "Nice · France",
  footer_location_en: "Nice · France",
  legal_notice_label_fr: "Mentions légales",
  legal_notice_label_en: "Legal notice",
  terms_label_fr: "CGV",
  terms_label_en: "Terms",
  privacy_label_fr: "Confidentialité",
  privacy_label_en: "Privacy",
  shipping_returns_label_fr: "Livraison & retours",
  shipping_returns_label_en: "Shipping & returns",

  legal_notice_title_fr: "Mentions légales",
  legal_notice_title_en: "Legal notice",
  legal_notice_body_fr: "À compléter dans l’administration avant la mise en ligne publique : éditeur du site, forme juridique, capital, siège social, SIREN/RCS, TVA, directeur de publication, hébergeur et coordonnées de contact.",
  legal_notice_body_en: "Complete this section in the administration before public launch: publisher, legal form, registered office, company registration, VAT, publication director, hosting provider and contact details.",
  terms_title_fr: "Conditions générales de vente",
  terms_title_en: "Terms and conditions of sale",
  terms_body_fr: "À compléter avant la mise en ligne publique : produits, prix, paiement, livraison, droit de rétractation, retours, remboursements, garanties, responsabilité, médiation et droit applicable.",
  terms_body_en: "Complete before public launch: products, prices, payment, shipping, withdrawal rights, returns, refunds, warranties, liability, mediation and applicable law.",
  privacy_title_fr: "Politique de confidentialité",
  privacy_title_en: "Privacy policy",
  privacy_body_fr: "À compléter avant la mise en ligne publique : responsable du traitement, données collectées, finalités, bases légales, destinataires, durées de conservation, droits des personnes et contact.",
  privacy_body_en: "Complete before public launch: data controller, collected data, purposes, legal bases, recipients, retention periods, data subject rights and contact.",
  shipping_returns_title_fr: "Livraison & retours",
  shipping_returns_title_en: "Shipping & returns",
  shipping_returns_body_fr: "Livraison en France métropolitaine selon le poids du colis. Complétez ici les délais indicatifs, conditions de retour, frais de retour et procédure de contact avant la mise en ligne publique.",
  shipping_returns_body_en: "Shipping in metropolitan France according to parcel weight. Complete indicative delivery times, return conditions, return costs and contact procedure before public launch.",

  phone: "",
  instagram: "",
  opening_hours: "11h–19h",
  support_email: "",
  shipping_packaging_weight_g: "120",
  free_shipping_threshold: "89",

  seo_title: "Ichigo Ichie — Maison de Matcha à Nice",
  seo_description: "Maison japonaise de matcha à Nice : carte sur place, matcha japonais et accessoires disponibles dans notre boutique en ligne.",

  theme_ink: "#26362d",
  theme_moss: "#486a4b",
  theme_moss_dark: "#294237",
  theme_paper: "#fffdf8",
  theme_soft: "#f5f2e8",
  theme_radius: "26",
};

const publicHeavySettingKeys = new Set([
  "legal_notice_body_fr",
  "legal_notice_body_en",
  "terms_body_fr",
  "terms_body_en",
  "privacy_body_fr",
  "privacy_body_en",
  "shipping_returns_body_fr",
  "shipping_returns_body_en",
]);

export function toPublicSiteSettings(settings: SiteSettings): SiteSettings {
  return Object.fromEntries(
    Object.entries(settings).filter(([key]) => !publicHeavySettingKeys.has(key)),
  );
}

export async function getSiteSettings(): Promise<SiteSettings> {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) return siteSettingDefaults;

  const supabase = createClient(url, key, {
    auth: { persistSession: false },
    global: { fetch: (input, init) => fetch(input, { ...init, cache: "no-store" }) },
  });
  const { data, error } = await supabase.from("site_settings").select("key,value");
  if (error || !data) return siteSettingDefaults;
  const values = Object.fromEntries(data.map((row) => [row.key, typeof row.value === "string" ? row.value : String(row.value ?? "")]));
  return { ...siteSettingDefaults, ...values };
}

export function settingEnabled(value: string | undefined, fallback = true) {
  if (value == null || value === "") return fallback;
  return value !== "false" && value !== "0";
}
